WavehareEPaper is no longer a PollingComponent
Fixes breaking ESPHome change as described in https://github.com/esphome/issues/issues/5256

Prevents error:

ValueError: Component ID epaper was not declared to inherit from Component, or was registered twice. Please create a bug report with your configuration.